main: su.gprb.nrmc.disannouncer.Disannouncer
name: Disannouncer
version: 1.1.2
description: The simplest PSA plugin out there
api-version: 1.19
load: STARTUP
author: https://github.com/undnull
website: https://github.com/undnull/disannouncer
commands:
  broadcast:
    description: Send a Public Service Announcement
    aliases: [psa, announce]
    permission: disannouncer.broadcast
    usage: /<command>
permissions:
  disannouncer.broadcast:
    default: op
